// <auto-generated />
using System;
using HomeVault.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HomeVaultDbContext))]
    [Migration("20261001112901_InitialVaults")]
    partial class InitialVaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("HomeVault.Infrastructure.Persistence.MembershipRow", b =>
                {
                    b.Property<Guid>("VaultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("VaultId", "ActorId");

                    b.ToTable("Memberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Membership_Actor", "ActorId <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Membership_Role", "Role IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("HomeVault.Infrastructure.Persistence.VaultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vaults", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vault_Id", "Id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Vault_Status", "Status IN (0, 1)");

                            t.HasCheckConstraint("CK_Vault_Type", "Type IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("HomeVault.Infrastructure.Persistence.MembershipRow", b =>
                {
                    b.HasOne("HomeVault.Infrastructure.Persistence.VaultRow", null)
                        .WithMany()
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
