using System.Security.Cryptography;
using HomeVault.Infrastructure.Encryption;

namespace HomeVault.Playground;

internal static class EncryptionKeyJourney
{
    internal static int Run(string[] args)
    {
        if (args.Length != 4 || args[1] is not ("initialize" or "verify" or "recover"))
        {
            Console.Error.WriteLine("Usage: encryption-keys initialize <new-ring> <export-directory> | verify <ring> <export-file> | recover <export-file> <new-ring>"); return 2;
        }
        if (!OperatingSystem.IsWindows() || Console.IsInputRedirected || Console.IsOutputRedirected)
        {
            Console.Error.WriteLine("Key operations require Windows and an interactive terminal."); return 1;
        }
        byte[]? secret = null; byte[]? confirmation = null;
        try
        {
            Console.WriteLine("Use a separately stored random 256-bit key generated by your password manager, not a password.");
            secret = ReadSecret();
            if (args[1] == "initialize")
            {
                Console.WriteLine("Enter the same key again."); confirmation = ReadSecret();
                if (!CryptographicOperations.FixedTimeEquals(secret, confirmation)) throw new InvalidOperationException();
            }
            var result = args[1] switch
            {
                "initialize" => EncryptionKeyOperations.Initialize(args[2], args[3], secret),
                "verify" => EncryptionKeyOperations.Verify(args[2], args[3], secret),
                _ => EncryptionKeyOperations.Recover(args[2], args[3], secret)
            };
            Console.WriteLine(result == KeyOperationOutcome.Succeeded ? "Key operation verified. Preserve the recovery export and separately stored secret." : "Key operation failed. Preserve known-good artifacts and check inputs, account and permissions.");
            return result == KeyOperationOutcome.Succeeded ? 0 : 1;
        }
        catch (Exception error) when (error is IOException or InvalidOperationException or ArgumentException)
        { Console.Error.WriteLine("Key operation failed. No secret details are displayed."); return 1; }
        finally { if (secret is not null) CryptographicOperations.ZeroMemory(secret); if (confirmation is not null) CryptographicOperations.ZeroMemory(confirmation); }
    }
    internal static byte[] ReadSecret(Func<bool, ConsoleKeyInfo>? readKey = null)
    {
        Console.Write("Recovery key (64 hex characters; hidden): ");
        var characters = new char[64]; var count = 0;
        try
        {
            while (true)
            {
                var key = readKey is null ? Console.ReadKey(intercept: true) : readKey(true);
                if (key.Key == ConsoleKey.Escape) throw new InvalidOperationException();
                if (key.Key == ConsoleKey.Enter) break;
                if (key.Key == ConsoleKey.Backspace) { if (count > 0) characters[--count] = '\0'; continue; }
                if (count >= characters.Length || !char.IsAsciiHexDigit(key.KeyChar)) throw new InvalidOperationException();
                characters[count++] = key.KeyChar;
            }
            Console.WriteLine();
            if (count != 64) throw new InvalidOperationException();
            return Convert.FromHexString(characters);
        }
        finally { Array.Clear(characters); }
    }
}
