<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.6.1" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/HomeVault.Domain/HomeVault.Domain.csproj" />
    <ProjectReference Include="../../src/HomeVault.Application/HomeVault.Application.csproj" />
  </ItemGroup>
</Project>
